// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfxdpbitanyuaowhiwzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmeGRwYml0YW55dWFvd2hpd3pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgzNzQyNzQsImV4cCI6MjA5Mzk1MDI3NH0.tDc_27_y2oplcA9xXsuHy8IeisdsO14W22C3NcSkn_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});